quarkus.http.port=9000
quarkus.debug.print-startup-times=false
quarkus.http.access-log.enabled=false
quarkus.http.access-log.pattern=YOUR_LOG_PATTERN
quarkus.datasource.db-kind=YOUR_DB_KIND
quarkus.datasource.username=YOUR_DB_USERNAME
quarkus.datasource.password=YOUR_PASSWORD
quarkus.datasource.jdbc.url=YOUR_JDBC_CONNECTION
quarkus.datasource.reactive.url=YOUR_REACTIVE_CONNECTION
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.smallrye-openapi.info-title=StaffOps Backend API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=OpenAPI documentation for the StaffOps backend services.
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger